version: "3.9"

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task4
    expose:
      - "5252"        # internal only; compose network
    ports:
      - "5252:5252"   # keep mapped in task4 (educational step)
    restart: unless-stopped

  front-end:
    build:
      context: ./front-end
    image: softy-pinko-front-end:task4
    expose:
      - "9000"
    ports:
      - "9000:9000"
    depends_on:
      - back-end
    restart: unless-stopped
